name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/cves/2015/CVE-2015-2794.yaml'
    - 'http/cves/2023/CVE-2023-42343.yaml'
    - 'http/cves/2023/CVE-2023-46574.yaml'
    - 'http/exposures/docker-daemon-exposed.yaml'
    - 'http/token-spray/api-openai.yaml'
    - 'http/vulnerabilities/ruijie/ruijie-nmc-sync-rce.yaml'
    - 'http/vulnerabilities/ruijie/ruijie-rg-eg-web-mis-rce.yaml'
    - 'http/vulnerabilities/yonyou/yonyou-ksoa-dept-sqli.yaml'
    - 'cloud/enum/aws-app-enum.yaml'
    - 'cloud/enum/aws-s3-bucket-enum.yaml'
    - 'cloud/enum/azure-db-enum.yaml'
    - 'cloud/enum/azure-vm-cloud-enum.yaml'
    - 'cloud/enum/azure-website-enum.yaml'
    - 'cloud/enum/gcp-app-engine-enum.yaml'
    - 'cloud/enum/gcp-bucket-enum.yaml'
    - 'cloud/enum/gcp-firebase-app-enum.yaml'
    - 'cloud/enum/gcp-firebase-rtdb-enum.yaml'
    - 'http/cves/2023/CVE-2023-41109.yaml'
    - 'network/misconfig/erlang-daemon.yaml'
    - 'code/cves/2019/CVE-2019-14287.yaml'
    - 'code/cves/2021/CVE-2021-3156.yaml'
    - 'http/cves/2020/CVE-2020-12124.yaml'
    - 'http/cves/2023/CVE-2023-50968.yaml'
    - 'http/cves/2023/CVE-2023-51467.yaml'
    - 'http/misconfiguration/cookies-without-httponly.yaml'
    - 'http/misconfiguration/php/php-composer-binary.yaml'
    - 'http/vulnerabilities/dahua/dahua-icc-backdoor-user.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
